source 'https://rubygems.org'

gem 'rails', '~> 6.1.0'
gem 'sqlite3'
gem 'puma'
gem 'sass-rails', '>= 6'
gem 'webpacker', '~> 5.0'
gem 'turbolinks', '~> 5'
gem 'jbuilder', '~> 2.7'
gem 'devise'

group :development, :test do
  gem 'byebug'
end

group :development do
  gem 'web-console', '>= 4.1.0'
  gem 'listen', '~> 3.3'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

group :test do
  gem 'capybara', '>= 3.26'
  gem 'selenium-webdriver'
  gem 'rspec-rails'
end

gem 'bootstrap', '~> 5.0.0'